### ISSUE TITLE
Permissions bot - Unregistered members can break the code

### ISSUE THREAD

**Issue by ErnWong** [AucklandRobotics/discord-bots-v2.0#3]
https://github.com/AucklandRobotics/discord-bots-v2.0/blob/44972ba206970bfd2fb4c4ec4b9b18a95b24ab09/permissions.js#L70-L88

The above catch block breaks if `error` does not have the `.message` field. For example, the following line causes `error` to equal the *string* `"NOT REGISTERED"` and not the *object* `{ message: "NOT REGISTERED" }` and would break the catch block.

https://github.com/AucklandRobotics/discord-bots-v2.0/blob/44972ba206970bfd2fb4c4ec4b9b18a95b24ab09/permissions.js#L124

One way around it would be to create a new `Error` class, such as this:
```js
class NotRegisteredError extends Error {
  constructor(message = 'Student ID is not registered in sheet', ...params) {
    super(message, ...params);
    this.name = 'NotRegisteredError';
  }
}
```
and use `throw new NotRegisteredError()` and `if (error instanceof NotRegisteredError)` instead of `throw 'NOT REGISTERED'` and  `if (error.message == 'NOT REGISTERED')`.

**Comment by DarkMatterMatt** [comment]
Alternatively you could use `error instanceof Error`
e.g. ```if ((error instanceof Error ? error.message : error) == 'NOT REGISTERED') {```

**Comment by ErnWong** [comment]
Just throwing it out here, we could also use:
```js
if (error === 'NOT REGISTERED')
```
and keep [this line](https://github.com/AucklandRobotics/discord-bots-v2.0/blob/44972ba206970bfd2fb4c4ec4b9b18a95b24ab09/permissions.js#L124) as is:
https://github.com/AucklandRobotics/discord-bots-v2.0/blob/44972ba206970bfd2fb4c4ec4b9b18a95b24ab09/permissions.js#L124

but I reckon we better change [the above line](https://github.com/AucklandRobotics/discord-bots-v2.0/blob/44972ba206970bfd2fb4c4ec4b9b18a95b24ab09/permissions.js#L124) to
```js
throw new Error('NOT REGISTERED');
```
or
```js
throw new NotRegisteredError();
```
Those would be nicer, than to throw some magic string around.

**Comment by DarkMatterMatt** [comment]
I vote `throw new Error('NOT REGISTERED');`
